# Generated by Django 5.2.1 on 2025-06-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0002_auto_20250608_update_models'),
        ('CRMapp', '0005_merge_20250608_1211'),
    ]

    operations = [
    ]
